Bug fixes, Basic actions
zaitra/vesna_experiment pull request #6
Opened 2023-08-22 14:15 UTC by DanGrizzly

Fixes bug on [issue #4](https://github.com/zaitra/vesna_experiment/issues/4)

Github actions added ([issue #5](https://github.com/zaitra/vesna_experiment/issues/5)):
1. precommit check for pull requests
2. poetry pytest runs for both push and pull request events

2023-08-25 11:27 UTC, DanGrizzly commented
For reasons made more complicated by poetry bugs and spinnaker sdk license agreement forbidding redistribution, using actions to run tests for most of the features is near impossible and was thus skipped.

Feel free to squash all of the above commits before merging, as it is a mess of trial and error.

2023-08-28 08:19 UTC, mjavorka requested changes

2023-08-28 08:19 UTC, mjavorka commented on src/camera_control/__main__.py
> +            structlog.get_logger().info("Querying whether to stop")
Initialize logger only once

2023-08-28 09:55 UTC, mjavorka approved these changes

2023-08-28 10:33 UTC, badanf approved these changes

2023-08-28 10:36 UTC, merged